version: '3.5'

services: 
  ubuntu:
    container_name: ubuntu_container
    build:
      context: ../dockerfiles/slave/
    depends_on: 
    - jenkins
    volumes: 
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - docker_network
    command: java -jar agent.jar -jnlpUrl http://192.168.44.44:8880/computer/Slave/jenkins-agent.jnlp -secret ea6486e68864717703ba474b8fbacf1f939ed7bf5b8d4be30447de4182a74974 -workDir "/home/"

  jenkins:
    container_name: jenkins_container
    image: jenkins/jenkins:jdk11
    ports:
    - "8880:8080"
    - "50000:50000"
    volumes: 
    - /home/panda/CICD_4/pandaenv/volumes/jenkins:/var/jenkins_home
    networks: 
    - docker_network

  artifactory:
    container_name: myjfrog_container
    image: docker.bintray.io/jfrog/artifactory-oss
    ports:
    - "8081:8081"
    - "8082:8082"
    volumes: 
    - /home/panda/CICD_4/pandaenv/volumes/artifactory:/var/opt/jfrog/artifactory
    networks: 
    - docker_network

  selenium_hub:
    container_name: selenium-hub_container
    image: selenium/hub
    ports:
    - "4444:4444"
    networks: 
    - docker_network

  selenium_node:
    container_name: selenium-node_container
    image: selenium/node-firefox
    networks: 
    - docker_network
    environment:  
    - HUB_HOST=selenium-hub_container
    - HUB_PORT=4444
    depends_on: 
    - selenium_hub
  
networks:
  docker_network:
    name: docker_network
    driver: bridge
    